package com.eco.mybatis.generate.entity;

import java.util.Date;

public class FlAgentinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.balance
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.create_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.device_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.device_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String deviceWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.parent_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.parent_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String parentWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.region
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.ry_token
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String ryToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.update_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.wx_icon
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String wxIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.wx_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.wx_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.appid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.open_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.uniond
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String uniond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.black_status
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Byte blackStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.fans_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Integer fansNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.user_type
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Byte userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.fans_order_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Integer fansOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.is_cash
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Byte isCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.is_chaquan
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Byte isChaquan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.is_order
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Byte isOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.public_user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private Integer publicUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.ali_pay_account
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String aliPayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_agentinfo.ali_pay_nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    private String aliPayNickName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.id
     *
     * @return the value of fl_agentinfo.id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.id
     *
     * @param id the value for fl_agentinfo.id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.balance
     *
     * @return the value of fl_agentinfo.balance
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.balance
     *
     * @param balance the value for fl_agentinfo.balance
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.create_time
     *
     * @return the value of fl_agentinfo.create_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.create_time
     *
     * @param createTime the value for fl_agentinfo.create_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.device_name
     *
     * @return the value of fl_agentinfo.device_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.device_name
     *
     * @param deviceName the value for fl_agentinfo.device_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.device_wxid
     *
     * @return the value of fl_agentinfo.device_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getDeviceWxid() {
        return deviceWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.device_wxid
     *
     * @param deviceWxid the value for fl_agentinfo.device_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setDeviceWxid(String deviceWxid) {
        this.deviceWxid = deviceWxid == null ? null : deviceWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.nick_name
     *
     * @return the value of fl_agentinfo.nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.nick_name
     *
     * @param nickName the value for fl_agentinfo.nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.parent_name
     *
     * @return the value of fl_agentinfo.parent_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.parent_name
     *
     * @param parentName the value for fl_agentinfo.parent_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.parent_wxid
     *
     * @return the value of fl_agentinfo.parent_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getParentWxid() {
        return parentWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.parent_wxid
     *
     * @param parentWxid the value for fl_agentinfo.parent_wxid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setParentWxid(String parentWxid) {
        this.parentWxid = parentWxid == null ? null : parentWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.region
     *
     * @return the value of fl_agentinfo.region
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.region
     *
     * @param region the value for fl_agentinfo.region
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.ry_token
     *
     * @return the value of fl_agentinfo.ry_token
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getRyToken() {
        return ryToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.ry_token
     *
     * @param ryToken the value for fl_agentinfo.ry_token
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setRyToken(String ryToken) {
        this.ryToken = ryToken == null ? null : ryToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.update_time
     *
     * @return the value of fl_agentinfo.update_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.update_time
     *
     * @param updateTime the value for fl_agentinfo.update_time
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.user_id
     *
     * @return the value of fl_agentinfo.user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.user_id
     *
     * @param userId the value for fl_agentinfo.user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.wx_icon
     *
     * @return the value of fl_agentinfo.wx_icon
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getWxIcon() {
        return wxIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.wx_icon
     *
     * @param wxIcon the value for fl_agentinfo.wx_icon
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setWxIcon(String wxIcon) {
        this.wxIcon = wxIcon == null ? null : wxIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.wx_id
     *
     * @return the value of fl_agentinfo.wx_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.wx_id
     *
     * @param wxId the value for fl_agentinfo.wx_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.wx_name
     *
     * @return the value of fl_agentinfo.wx_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.wx_name
     *
     * @param wxName the value for fl_agentinfo.wx_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.appid
     *
     * @return the value of fl_agentinfo.appid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.appid
     *
     * @param appid the value for fl_agentinfo.appid
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.open_id
     *
     * @return the value of fl_agentinfo.open_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.open_id
     *
     * @param openId the value for fl_agentinfo.open_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.uniond
     *
     * @return the value of fl_agentinfo.uniond
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getUniond() {
        return uniond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.uniond
     *
     * @param uniond the value for fl_agentinfo.uniond
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setUniond(String uniond) {
        this.uniond = uniond == null ? null : uniond.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.black_status
     *
     * @return the value of fl_agentinfo.black_status
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Byte getBlackStatus() {
        return blackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.black_status
     *
     * @param blackStatus the value for fl_agentinfo.black_status
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setBlackStatus(Byte blackStatus) {
        this.blackStatus = blackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.fans_num
     *
     * @return the value of fl_agentinfo.fans_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Integer getFansNum() {
        return fansNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.fans_num
     *
     * @param fansNum the value for fl_agentinfo.fans_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setFansNum(Integer fansNum) {
        this.fansNum = fansNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.user_type
     *
     * @return the value of fl_agentinfo.user_type
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Byte getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.user_type
     *
     * @param userType the value for fl_agentinfo.user_type
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setUserType(Byte userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.fans_order_num
     *
     * @return the value of fl_agentinfo.fans_order_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Integer getFansOrderNum() {
        return fansOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.fans_order_num
     *
     * @param fansOrderNum the value for fl_agentinfo.fans_order_num
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setFansOrderNum(Integer fansOrderNum) {
        this.fansOrderNum = fansOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.is_cash
     *
     * @return the value of fl_agentinfo.is_cash
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Byte getIsCash() {
        return isCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.is_cash
     *
     * @param isCash the value for fl_agentinfo.is_cash
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setIsCash(Byte isCash) {
        this.isCash = isCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.is_chaquan
     *
     * @return the value of fl_agentinfo.is_chaquan
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Byte getIsChaquan() {
        return isChaquan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.is_chaquan
     *
     * @param isChaquan the value for fl_agentinfo.is_chaquan
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setIsChaquan(Byte isChaquan) {
        this.isChaquan = isChaquan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.is_order
     *
     * @return the value of fl_agentinfo.is_order
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Byte getIsOrder() {
        return isOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.is_order
     *
     * @param isOrder the value for fl_agentinfo.is_order
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setIsOrder(Byte isOrder) {
        this.isOrder = isOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.public_user_id
     *
     * @return the value of fl_agentinfo.public_user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public Integer getPublicUserId() {
        return publicUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.public_user_id
     *
     * @param publicUserId the value for fl_agentinfo.public_user_id
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setPublicUserId(Integer publicUserId) {
        this.publicUserId = publicUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.ali_pay_account
     *
     * @return the value of fl_agentinfo.ali_pay_account
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getAliPayAccount() {
        return aliPayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.ali_pay_account
     *
     * @param aliPayAccount the value for fl_agentinfo.ali_pay_account
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setAliPayAccount(String aliPayAccount) {
        this.aliPayAccount = aliPayAccount == null ? null : aliPayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_agentinfo.ali_pay_nick_name
     *
     * @return the value of fl_agentinfo.ali_pay_nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public String getAliPayNickName() {
        return aliPayNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_agentinfo.ali_pay_nick_name
     *
     * @param aliPayNickName the value for fl_agentinfo.ali_pay_nick_name
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    public void setAliPayNickName(String aliPayNickName) {
        this.aliPayNickName = aliPayNickName == null ? null : aliPayNickName.trim();
    }
}