package com.eco.mybatis.generate.entity;

import java.util.Date;

public class FlWorkUserCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.usermark_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer usermarkWorkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.ratio
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Double ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_pay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderPayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_cancel_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderCancelNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_settle_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderSettleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_delay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderDelayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_refund_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderRefundNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_order_search
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkOrderSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_cash_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkCashNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_share_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkShareNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_share_buy_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer wechatWorkShareBuyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_search_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private String wechatWorkSearchWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_cash_money
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Double wechatWorkCashMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_work_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date wechatWorkSearchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.sign_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer signNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.taobao_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer taobaoNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date wechatSearchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.order_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.cash_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Date cashTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_open_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Byte wechatOpenUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.app_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Byte appUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user_count.wechat_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    private Byte wechatUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_id
     *
     * @return the value of fl_work_user_count.wechat_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkId() {
        return wechatWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_id
     *
     * @param wechatWorkId the value for fl_work_user_count.wechat_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkId(Integer wechatWorkId) {
        this.wechatWorkId = wechatWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.usermark_work_id
     *
     * @return the value of fl_work_user_count.usermark_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getUsermarkWorkId() {
        return usermarkWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.usermark_work_id
     *
     * @param usermarkWorkId the value for fl_work_user_count.usermark_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setUsermarkWorkId(Integer usermarkWorkId) {
        this.usermarkWorkId = usermarkWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.ratio
     *
     * @return the value of fl_work_user_count.ratio
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Double getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.ratio
     *
     * @param ratio the value for fl_work_user_count.ratio
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setRatio(Double ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_pay_number
     *
     * @return the value of fl_work_user_count.wechat_work_order_pay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderPayNumber() {
        return wechatWorkOrderPayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_pay_number
     *
     * @param wechatWorkOrderPayNumber the value for fl_work_user_count.wechat_work_order_pay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderPayNumber(Integer wechatWorkOrderPayNumber) {
        this.wechatWorkOrderPayNumber = wechatWorkOrderPayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_cancel_number
     *
     * @return the value of fl_work_user_count.wechat_work_order_cancel_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderCancelNumber() {
        return wechatWorkOrderCancelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_cancel_number
     *
     * @param wechatWorkOrderCancelNumber the value for fl_work_user_count.wechat_work_order_cancel_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderCancelNumber(Integer wechatWorkOrderCancelNumber) {
        this.wechatWorkOrderCancelNumber = wechatWorkOrderCancelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_settle_number
     *
     * @return the value of fl_work_user_count.wechat_work_order_settle_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderSettleNumber() {
        return wechatWorkOrderSettleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_settle_number
     *
     * @param wechatWorkOrderSettleNumber the value for fl_work_user_count.wechat_work_order_settle_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderSettleNumber(Integer wechatWorkOrderSettleNumber) {
        this.wechatWorkOrderSettleNumber = wechatWorkOrderSettleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_delay_number
     *
     * @return the value of fl_work_user_count.wechat_work_order_delay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderDelayNumber() {
        return wechatWorkOrderDelayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_delay_number
     *
     * @param wechatWorkOrderDelayNumber the value for fl_work_user_count.wechat_work_order_delay_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderDelayNumber(Integer wechatWorkOrderDelayNumber) {
        this.wechatWorkOrderDelayNumber = wechatWorkOrderDelayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_refund_number
     *
     * @return the value of fl_work_user_count.wechat_work_order_refund_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderRefundNumber() {
        return wechatWorkOrderRefundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_refund_number
     *
     * @param wechatWorkOrderRefundNumber the value for fl_work_user_count.wechat_work_order_refund_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderRefundNumber(Integer wechatWorkOrderRefundNumber) {
        this.wechatWorkOrderRefundNumber = wechatWorkOrderRefundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_order_search
     *
     * @return the value of fl_work_user_count.wechat_work_order_search
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkOrderSearch() {
        return wechatWorkOrderSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_order_search
     *
     * @param wechatWorkOrderSearch the value for fl_work_user_count.wechat_work_order_search
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkOrderSearch(Integer wechatWorkOrderSearch) {
        this.wechatWorkOrderSearch = wechatWorkOrderSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_cash_number
     *
     * @return the value of fl_work_user_count.wechat_work_cash_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkCashNumber() {
        return wechatWorkCashNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_cash_number
     *
     * @param wechatWorkCashNumber the value for fl_work_user_count.wechat_work_cash_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkCashNumber(Integer wechatWorkCashNumber) {
        this.wechatWorkCashNumber = wechatWorkCashNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_share_number
     *
     * @return the value of fl_work_user_count.wechat_work_share_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkShareNumber() {
        return wechatWorkShareNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_share_number
     *
     * @param wechatWorkShareNumber the value for fl_work_user_count.wechat_work_share_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkShareNumber(Integer wechatWorkShareNumber) {
        this.wechatWorkShareNumber = wechatWorkShareNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_share_buy_number
     *
     * @return the value of fl_work_user_count.wechat_work_share_buy_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getWechatWorkShareBuyNumber() {
        return wechatWorkShareBuyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_share_buy_number
     *
     * @param wechatWorkShareBuyNumber the value for fl_work_user_count.wechat_work_share_buy_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkShareBuyNumber(Integer wechatWorkShareBuyNumber) {
        this.wechatWorkShareBuyNumber = wechatWorkShareBuyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_search_wxid
     *
     * @return the value of fl_work_user_count.wechat_work_search_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public String getWechatWorkSearchWxid() {
        return wechatWorkSearchWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_search_wxid
     *
     * @param wechatWorkSearchWxid the value for fl_work_user_count.wechat_work_search_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkSearchWxid(String wechatWorkSearchWxid) {
        this.wechatWorkSearchWxid = wechatWorkSearchWxid == null ? null : wechatWorkSearchWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_cash_money
     *
     * @return the value of fl_work_user_count.wechat_work_cash_money
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Double getWechatWorkCashMoney() {
        return wechatWorkCashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_cash_money
     *
     * @param wechatWorkCashMoney the value for fl_work_user_count.wechat_work_cash_money
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkCashMoney(Double wechatWorkCashMoney) {
        this.wechatWorkCashMoney = wechatWorkCashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_work_search_time
     *
     * @return the value of fl_work_user_count.wechat_work_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getWechatWorkSearchTime() {
        return wechatWorkSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_work_search_time
     *
     * @param wechatWorkSearchTime the value for fl_work_user_count.wechat_work_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatWorkSearchTime(Date wechatWorkSearchTime) {
        this.wechatWorkSearchTime = wechatWorkSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.sign_number
     *
     * @return the value of fl_work_user_count.sign_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getSignNumber() {
        return signNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.sign_number
     *
     * @param signNumber the value for fl_work_user_count.sign_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setSignNumber(Integer signNumber) {
        this.signNumber = signNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.taobao_number
     *
     * @return the value of fl_work_user_count.taobao_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getTaobaoNumber() {
        return taobaoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.taobao_number
     *
     * @param taobaoNumber the value for fl_work_user_count.taobao_number
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setTaobaoNumber(Integer taobaoNumber) {
        this.taobaoNumber = taobaoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.create_time
     *
     * @return the value of fl_work_user_count.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.create_time
     *
     * @param createTime the value for fl_work_user_count.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.update_time
     *
     * @return the value of fl_work_user_count.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.update_time
     *
     * @param updateTime the value for fl_work_user_count.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_search_time
     *
     * @return the value of fl_work_user_count.wechat_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getWechatSearchTime() {
        return wechatSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_search_time
     *
     * @param wechatSearchTime the value for fl_work_user_count.wechat_search_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatSearchTime(Date wechatSearchTime) {
        this.wechatSearchTime = wechatSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.order_time
     *
     * @return the value of fl_work_user_count.order_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.order_time
     *
     * @param orderTime the value for fl_work_user_count.order_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.user_id
     *
     * @return the value of fl_work_user_count.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.user_id
     *
     * @param userId the value for fl_work_user_count.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.cash_time
     *
     * @return the value of fl_work_user_count.cash_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Date getCashTime() {
        return cashTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.cash_time
     *
     * @param cashTime the value for fl_work_user_count.cash_time
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setCashTime(Date cashTime) {
        this.cashTime = cashTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_open_user
     *
     * @return the value of fl_work_user_count.wechat_open_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Byte getWechatOpenUser() {
        return wechatOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_open_user
     *
     * @param wechatOpenUser the value for fl_work_user_count.wechat_open_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatOpenUser(Byte wechatOpenUser) {
        this.wechatOpenUser = wechatOpenUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.app_user
     *
     * @return the value of fl_work_user_count.app_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Byte getAppUser() {
        return appUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.app_user
     *
     * @param appUser the value for fl_work_user_count.app_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setAppUser(Byte appUser) {
        this.appUser = appUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user_count.wechat_user
     *
     * @return the value of fl_work_user_count.wechat_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public Byte getWechatUser() {
        return wechatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user_count.wechat_user
     *
     * @param wechatUser the value for fl_work_user_count.wechat_user
     *
     * @mbggenerated Wed Jun 10 15:38:05 CST 2020
     */
    public void setWechatUser(Byte wechatUser) {
        this.wechatUser = wechatUser;
    }
}