package com.eco.mybatis.generate.entity;

import java.util.Date;

public class FlWorkdevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String adzonePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.chatroom_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String chatroomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.cloed_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Date cloedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.device_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.new_user_cash_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer newUserCashOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.new_user_sign_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer newUserSignOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.new_user_template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Byte newUserTemplateOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.online
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Byte online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.origin_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String originWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.status
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer templateOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.wx_work_icon
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String wxWorkIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.wx_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String wxWorkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.wx_work_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String wxWorkName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.xh_adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String xhAdzonePid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.datapay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer datapayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.pay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.payplan_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer payplanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.taobao_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer taobaoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.xh_taobao_plan
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private Integer xhTaobaoPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_workdevice.dg_url
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    private String dgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.id
     *
     * @return the value of fl_workdevice.id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.id
     *
     * @param id the value for fl_workdevice.id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.adzone_pid
     *
     * @return the value of fl_workdevice.adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getAdzonePid() {
        return adzonePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.adzone_pid
     *
     * @param adzonePid the value for fl_workdevice.adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setAdzonePid(String adzonePid) {
        this.adzonePid = adzonePid == null ? null : adzonePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.chatroom_id
     *
     * @return the value of fl_workdevice.chatroom_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getChatroomId() {
        return chatroomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.chatroom_id
     *
     * @param chatroomId the value for fl_workdevice.chatroom_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setChatroomId(String chatroomId) {
        this.chatroomId = chatroomId == null ? null : chatroomId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.cloed_time
     *
     * @return the value of fl_workdevice.cloed_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Date getCloedTime() {
        return cloedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.cloed_time
     *
     * @param cloedTime the value for fl_workdevice.cloed_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setCloedTime(Date cloedTime) {
        this.cloedTime = cloedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.create_time
     *
     * @return the value of fl_workdevice.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.create_time
     *
     * @param createTime the value for fl_workdevice.create_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.device_name
     *
     * @return the value of fl_workdevice.device_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.device_name
     *
     * @param deviceName the value for fl_workdevice.device_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.new_user_cash_off
     *
     * @return the value of fl_workdevice.new_user_cash_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getNewUserCashOff() {
        return newUserCashOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.new_user_cash_off
     *
     * @param newUserCashOff the value for fl_workdevice.new_user_cash_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setNewUserCashOff(Integer newUserCashOff) {
        this.newUserCashOff = newUserCashOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.new_user_sign_off
     *
     * @return the value of fl_workdevice.new_user_sign_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getNewUserSignOff() {
        return newUserSignOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.new_user_sign_off
     *
     * @param newUserSignOff the value for fl_workdevice.new_user_sign_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setNewUserSignOff(Integer newUserSignOff) {
        this.newUserSignOff = newUserSignOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.new_user_template_off
     *
     * @return the value of fl_workdevice.new_user_template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Byte getNewUserTemplateOff() {
        return newUserTemplateOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.new_user_template_off
     *
     * @param newUserTemplateOff the value for fl_workdevice.new_user_template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setNewUserTemplateOff(Byte newUserTemplateOff) {
        this.newUserTemplateOff = newUserTemplateOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.online
     *
     * @return the value of fl_workdevice.online
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Byte getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.online
     *
     * @param online the value for fl_workdevice.online
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setOnline(Byte online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.origin_wxid
     *
     * @return the value of fl_workdevice.origin_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getOriginWxid() {
        return originWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.origin_wxid
     *
     * @param originWxid the value for fl_workdevice.origin_wxid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setOriginWxid(String originWxid) {
        this.originWxid = originWxid == null ? null : originWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.status
     *
     * @return the value of fl_workdevice.status
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.status
     *
     * @param status the value for fl_workdevice.status
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.template_off
     *
     * @return the value of fl_workdevice.template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getTemplateOff() {
        return templateOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.template_off
     *
     * @param templateOff the value for fl_workdevice.template_off
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setTemplateOff(Integer templateOff) {
        this.templateOff = templateOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.update_time
     *
     * @return the value of fl_workdevice.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.update_time
     *
     * @param updateTime the value for fl_workdevice.update_time
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.user_id
     *
     * @return the value of fl_workdevice.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.user_id
     *
     * @param userId the value for fl_workdevice.user_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.wx_work_icon
     *
     * @return the value of fl_workdevice.wx_work_icon
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getWxWorkIcon() {
        return wxWorkIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.wx_work_icon
     *
     * @param wxWorkIcon the value for fl_workdevice.wx_work_icon
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setWxWorkIcon(String wxWorkIcon) {
        this.wxWorkIcon = wxWorkIcon == null ? null : wxWorkIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.wx_work_id
     *
     * @return the value of fl_workdevice.wx_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getWxWorkId() {
        return wxWorkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.wx_work_id
     *
     * @param wxWorkId the value for fl_workdevice.wx_work_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setWxWorkId(String wxWorkId) {
        this.wxWorkId = wxWorkId == null ? null : wxWorkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.wx_work_name
     *
     * @return the value of fl_workdevice.wx_work_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getWxWorkName() {
        return wxWorkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.wx_work_name
     *
     * @param wxWorkName the value for fl_workdevice.wx_work_name
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setWxWorkName(String wxWorkName) {
        this.wxWorkName = wxWorkName == null ? null : wxWorkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.xh_adzone_pid
     *
     * @return the value of fl_workdevice.xh_adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getXhAdzonePid() {
        return xhAdzonePid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.xh_adzone_pid
     *
     * @param xhAdzonePid the value for fl_workdevice.xh_adzone_pid
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setXhAdzonePid(String xhAdzonePid) {
        this.xhAdzonePid = xhAdzonePid == null ? null : xhAdzonePid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.datapay_id
     *
     * @return the value of fl_workdevice.datapay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getDatapayId() {
        return datapayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.datapay_id
     *
     * @param datapayId the value for fl_workdevice.datapay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setDatapayId(Integer datapayId) {
        this.datapayId = datapayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.pay_id
     *
     * @return the value of fl_workdevice.pay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.pay_id
     *
     * @param payId the value for fl_workdevice.pay_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.payplan_id
     *
     * @return the value of fl_workdevice.payplan_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getPayplanId() {
        return payplanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.payplan_id
     *
     * @param payplanId the value for fl_workdevice.payplan_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setPayplanId(Integer payplanId) {
        this.payplanId = payplanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.taobao_id
     *
     * @return the value of fl_workdevice.taobao_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getTaobaoId() {
        return taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.taobao_id
     *
     * @param taobaoId the value for fl_workdevice.taobao_id
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setTaobaoId(Integer taobaoId) {
        this.taobaoId = taobaoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.xh_taobao_plan
     *
     * @return the value of fl_workdevice.xh_taobao_plan
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public Integer getXhTaobaoPlan() {
        return xhTaobaoPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.xh_taobao_plan
     *
     * @param xhTaobaoPlan the value for fl_workdevice.xh_taobao_plan
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setXhTaobaoPlan(Integer xhTaobaoPlan) {
        this.xhTaobaoPlan = xhTaobaoPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_workdevice.dg_url
     *
     * @return the value of fl_workdevice.dg_url
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public String getDgUrl() {
        return dgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_workdevice.dg_url
     *
     * @param dgUrl the value for fl_workdevice.dg_url
     *
     * @mbggenerated Wed Jun 10 15:38:53 CST 2020
     */
    public void setDgUrl(String dgUrl) {
        this.dgUrl = dgUrl == null ? null : dgUrl.trim();
    }
}