package com.eco.mybatis.generate.entity;

import java.util.Date;

public class FlWorkUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.ali_pay_account
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String aliPayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.ali_pay_nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String aliPayNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.balance
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Double balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.black_status
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Byte blackStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.create_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.device_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.device_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String deviceWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.parent_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.parent_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String parentWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.update_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.wx_icon
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String wxIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.wx_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String wxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.wx_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private String wxName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.wx_type
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Byte wxType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_work_user.public_user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    private Integer publicUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.id
     *
     * @return the value of fl_work_user.id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.id
     *
     * @param id the value for fl_work_user.id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.ali_pay_account
     *
     * @return the value of fl_work_user.ali_pay_account
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getAliPayAccount() {
        return aliPayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.ali_pay_account
     *
     * @param aliPayAccount the value for fl_work_user.ali_pay_account
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setAliPayAccount(String aliPayAccount) {
        this.aliPayAccount = aliPayAccount == null ? null : aliPayAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.ali_pay_nick_name
     *
     * @return the value of fl_work_user.ali_pay_nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getAliPayNickName() {
        return aliPayNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.ali_pay_nick_name
     *
     * @param aliPayNickName the value for fl_work_user.ali_pay_nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setAliPayNickName(String aliPayNickName) {
        this.aliPayNickName = aliPayNickName == null ? null : aliPayNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.balance
     *
     * @return the value of fl_work_user.balance
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.balance
     *
     * @param balance the value for fl_work_user.balance
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.black_status
     *
     * @return the value of fl_work_user.black_status
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Byte getBlackStatus() {
        return blackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.black_status
     *
     * @param blackStatus the value for fl_work_user.black_status
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setBlackStatus(Byte blackStatus) {
        this.blackStatus = blackStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.create_time
     *
     * @return the value of fl_work_user.create_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.create_time
     *
     * @param createTime the value for fl_work_user.create_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.device_name
     *
     * @return the value of fl_work_user.device_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.device_name
     *
     * @param deviceName the value for fl_work_user.device_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.device_wxid
     *
     * @return the value of fl_work_user.device_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getDeviceWxid() {
        return deviceWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.device_wxid
     *
     * @param deviceWxid the value for fl_work_user.device_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setDeviceWxid(String deviceWxid) {
        this.deviceWxid = deviceWxid == null ? null : deviceWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.nick_name
     *
     * @return the value of fl_work_user.nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.nick_name
     *
     * @param nickName the value for fl_work_user.nick_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.parent_name
     *
     * @return the value of fl_work_user.parent_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.parent_name
     *
     * @param parentName the value for fl_work_user.parent_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.parent_wxid
     *
     * @return the value of fl_work_user.parent_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getParentWxid() {
        return parentWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.parent_wxid
     *
     * @param parentWxid the value for fl_work_user.parent_wxid
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setParentWxid(String parentWxid) {
        this.parentWxid = parentWxid == null ? null : parentWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.update_time
     *
     * @return the value of fl_work_user.update_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.update_time
     *
     * @param updateTime the value for fl_work_user.update_time
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.user_id
     *
     * @return the value of fl_work_user.user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.user_id
     *
     * @param userId the value for fl_work_user.user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.wx_icon
     *
     * @return the value of fl_work_user.wx_icon
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getWxIcon() {
        return wxIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.wx_icon
     *
     * @param wxIcon the value for fl_work_user.wx_icon
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setWxIcon(String wxIcon) {
        this.wxIcon = wxIcon == null ? null : wxIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.wx_id
     *
     * @return the value of fl_work_user.wx_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getWxId() {
        return wxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.wx_id
     *
     * @param wxId the value for fl_work_user.wx_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setWxId(String wxId) {
        this.wxId = wxId == null ? null : wxId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.wx_name
     *
     * @return the value of fl_work_user.wx_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public String getWxName() {
        return wxName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.wx_name
     *
     * @param wxName the value for fl_work_user.wx_name
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setWxName(String wxName) {
        this.wxName = wxName == null ? null : wxName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.wx_type
     *
     * @return the value of fl_work_user.wx_type
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Byte getWxType() {
        return wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.wx_type
     *
     * @param wxType the value for fl_work_user.wx_type
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setWxType(Byte wxType) {
        this.wxType = wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_work_user.public_user_id
     *
     * @return the value of fl_work_user.public_user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public Integer getPublicUserId() {
        return publicUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_work_user.public_user_id
     *
     * @param publicUserId the value for fl_work_user.public_user_id
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    public void setPublicUserId(Integer publicUserId) {
        this.publicUserId = publicUserId;
    }
}