package com.eco.mybatis.generate.entity;

import java.util.Date;

public class FlWxCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.usermark_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer usermarkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.ratio
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_pay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderPayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_cancel_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderCancelNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_settle_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderSettleNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_delay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderDelayNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_refund_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderRefundNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_order_search
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatOrderSearch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_cash_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatCashNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_share_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatShareNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_share_buy_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer wechatShareBuyNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_search_wxid
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private String wechatSearchWxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_cash_money
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Double wechatCashMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.wechat_search_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Date wechatSearchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.sign_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer signNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.taobao_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Integer taobaoNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.create_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fl_wx_count.update_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_id
     *
     * @return the value of fl_wx_count.wechat_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_id
     *
     * @param wechatId the value for fl_wx_count.wechat_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatId(Integer wechatId) {
        this.wechatId = wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.usermark_id
     *
     * @return the value of fl_wx_count.usermark_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getUsermarkId() {
        return usermarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.usermark_id
     *
     * @param usermarkId the value for fl_wx_count.usermark_id
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setUsermarkId(Integer usermarkId) {
        this.usermarkId = usermarkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.ratio
     *
     * @return the value of fl_wx_count.ratio
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.ratio
     *
     * @param ratio the value for fl_wx_count.ratio
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setRatio(Integer ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_pay_number
     *
     * @return the value of fl_wx_count.wechat_order_pay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderPayNumber() {
        return wechatOrderPayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_pay_number
     *
     * @param wechatOrderPayNumber the value for fl_wx_count.wechat_order_pay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderPayNumber(Integer wechatOrderPayNumber) {
        this.wechatOrderPayNumber = wechatOrderPayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_cancel_number
     *
     * @return the value of fl_wx_count.wechat_order_cancel_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderCancelNumber() {
        return wechatOrderCancelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_cancel_number
     *
     * @param wechatOrderCancelNumber the value for fl_wx_count.wechat_order_cancel_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderCancelNumber(Integer wechatOrderCancelNumber) {
        this.wechatOrderCancelNumber = wechatOrderCancelNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_settle_number
     *
     * @return the value of fl_wx_count.wechat_order_settle_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderSettleNumber() {
        return wechatOrderSettleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_settle_number
     *
     * @param wechatOrderSettleNumber the value for fl_wx_count.wechat_order_settle_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderSettleNumber(Integer wechatOrderSettleNumber) {
        this.wechatOrderSettleNumber = wechatOrderSettleNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_delay_number
     *
     * @return the value of fl_wx_count.wechat_order_delay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderDelayNumber() {
        return wechatOrderDelayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_delay_number
     *
     * @param wechatOrderDelayNumber the value for fl_wx_count.wechat_order_delay_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderDelayNumber(Integer wechatOrderDelayNumber) {
        this.wechatOrderDelayNumber = wechatOrderDelayNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_refund_number
     *
     * @return the value of fl_wx_count.wechat_order_refund_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderRefundNumber() {
        return wechatOrderRefundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_refund_number
     *
     * @param wechatOrderRefundNumber the value for fl_wx_count.wechat_order_refund_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderRefundNumber(Integer wechatOrderRefundNumber) {
        this.wechatOrderRefundNumber = wechatOrderRefundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_order_search
     *
     * @return the value of fl_wx_count.wechat_order_search
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatOrderSearch() {
        return wechatOrderSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_order_search
     *
     * @param wechatOrderSearch the value for fl_wx_count.wechat_order_search
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatOrderSearch(Integer wechatOrderSearch) {
        this.wechatOrderSearch = wechatOrderSearch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_cash_number
     *
     * @return the value of fl_wx_count.wechat_cash_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatCashNumber() {
        return wechatCashNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_cash_number
     *
     * @param wechatCashNumber the value for fl_wx_count.wechat_cash_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatCashNumber(Integer wechatCashNumber) {
        this.wechatCashNumber = wechatCashNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_share_number
     *
     * @return the value of fl_wx_count.wechat_share_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatShareNumber() {
        return wechatShareNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_share_number
     *
     * @param wechatShareNumber the value for fl_wx_count.wechat_share_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatShareNumber(Integer wechatShareNumber) {
        this.wechatShareNumber = wechatShareNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_share_buy_number
     *
     * @return the value of fl_wx_count.wechat_share_buy_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getWechatShareBuyNumber() {
        return wechatShareBuyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_share_buy_number
     *
     * @param wechatShareBuyNumber the value for fl_wx_count.wechat_share_buy_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatShareBuyNumber(Integer wechatShareBuyNumber) {
        this.wechatShareBuyNumber = wechatShareBuyNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_search_wxid
     *
     * @return the value of fl_wx_count.wechat_search_wxid
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public String getWechatSearchWxid() {
        return wechatSearchWxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_search_wxid
     *
     * @param wechatSearchWxid the value for fl_wx_count.wechat_search_wxid
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatSearchWxid(String wechatSearchWxid) {
        this.wechatSearchWxid = wechatSearchWxid == null ? null : wechatSearchWxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_cash_money
     *
     * @return the value of fl_wx_count.wechat_cash_money
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Double getWechatCashMoney() {
        return wechatCashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_cash_money
     *
     * @param wechatCashMoney the value for fl_wx_count.wechat_cash_money
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatCashMoney(Double wechatCashMoney) {
        this.wechatCashMoney = wechatCashMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.wechat_search_time
     *
     * @return the value of fl_wx_count.wechat_search_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Date getWechatSearchTime() {
        return wechatSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.wechat_search_time
     *
     * @param wechatSearchTime the value for fl_wx_count.wechat_search_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setWechatSearchTime(Date wechatSearchTime) {
        this.wechatSearchTime = wechatSearchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.sign_number
     *
     * @return the value of fl_wx_count.sign_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getSignNumber() {
        return signNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.sign_number
     *
     * @param signNumber the value for fl_wx_count.sign_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setSignNumber(Integer signNumber) {
        this.signNumber = signNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.taobao_number
     *
     * @return the value of fl_wx_count.taobao_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Integer getTaobaoNumber() {
        return taobaoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.taobao_number
     *
     * @param taobaoNumber the value for fl_wx_count.taobao_number
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setTaobaoNumber(Integer taobaoNumber) {
        this.taobaoNumber = taobaoNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.create_time
     *
     * @return the value of fl_wx_count.create_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.create_time
     *
     * @param createTime the value for fl_wx_count.create_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fl_wx_count.update_time
     *
     * @return the value of fl_wx_count.update_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fl_wx_count.update_time
     *
     * @param updateTime the value for fl_wx_count.update_time
     *
     * @mbggenerated Tue Jun 16 17:18:25 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}