package com.eco.mybatis.generate.mapper;

import com.eco.mybatis.generate.entity.FlAgentinfo;

public interface FlAgentinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    int insert(FlAgentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    int insertSelective(FlAgentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    FlAgentinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    int updateByPrimaryKeySelective(FlAgentinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_agentinfo
     *
     * @mbggenerated Wed Jun 17 11:01:45 CST 2020
     */
    int updateByPrimaryKey(FlAgentinfo record);
}