package com.eco.mybatis.generate.mapper;

import com.eco.mybatis.generate.entity.FlWorkUser;

public interface FlWorkUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    int insert(FlWorkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    int insertSelective(FlWorkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    FlWorkUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    int updateByPrimaryKeySelective(FlWorkUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fl_work_user
     *
     * @mbggenerated Mon Jun 08 17:39:05 CST 2020
     */
    int updateByPrimaryKey(FlWorkUser record);
}